// CineTales — AIPitch component.
// Click "Why watch this?" to fetch a spoiler-free 3-bullet AI pitch
// from /api/ai-pitch. No login required. Caches client-side per title.

import { useState } from "react";

export default function AIPitch({ title, year, overview, genres = [], type = "movie" }) {
  const [loading, setLoading] = useState(false);
  const [bullets, setBullets] = useState(null);
  const [error, setError] = useState("");

  async function generate() {
    if (loading || bullets) return;
    setLoading(true);
    setError("");
    try {
      const res = await fetch("/api/ai-pitch", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title, year, overview, genres, type }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed");
      setBullets(data.bullets || []);
    } catch (e) {
      setError("Couldn't generate. Try again.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="rounded-2xl bg-surface border border-border p-5 md:p-6 relative overflow-hidden">
      {/* Subtle accent glow corner */}
      <div className="absolute -top-12 -right-12 w-40 h-40 rounded-full bg-accent-dim blur-3xl pointer-events-none" />

      <div className="relative flex items-start justify-between gap-4 mb-4">
        <div>
          <p className="font-mono text-[10px] uppercase tracking-widest2 text-accent mb-1">
            ✦ AI Pitch
          </p>
          <p className="text-sm text-text-2">
            Why watch this? A spoiler-free take, generated for you.
          </p>
        </div>
        {!bullets && !loading && (
          <button
            onClick={generate}
            className="shrink-0 px-4 py-2 rounded-full bg-accent text-white text-sm font-medium hover:bg-accent-hover btn-press whitespace-nowrap"
          >
            Generate →
          </button>
        )}
      </div>

      {loading && (
        <div className="space-y-2.5 relative">
          {[0, 1, 2].map((i) => (
            <div
              key={i}
              className="h-4 rounded shimmer"
              style={{ width: `${85 - i * 8}%` }}
            />
          ))}
          <p className="font-mono text-[10px] text-text-3 mt-3">
            Asking the AI…
          </p>
        </div>
      )}

      {error && (
        <div className="relative">
          <p className="text-sm text-skip mb-2">{error}</p>
          <button
            onClick={generate}
            className="text-xs text-accent hover:text-accent-hover underline-offset-4 hover:underline"
          >
            Try again
          </button>
        </div>
      )}

      {bullets && bullets.length > 0 && (
        <ul className="relative space-y-2.5 animate-fade-in">
          {bullets.map((b, i) => (
            <li key={i} className="flex gap-3 text-sm text-text-1 leading-relaxed">
              <span className="text-accent font-mono shrink-0 mt-0.5">→</span>
              <span>{b}</span>
            </li>
          ))}
          <p className="font-mono text-[10px] text-text-3 pt-2 border-t border-border mt-4">
            Generated by Groq · llama-3.3-70b · spoiler-free
          </p>
        </ul>
      )}
    </div>
  );
}
