// CineTales — AIPitch component.
// Auto-generates a spoiler-free 3-bullet AI pitch from /api/ai-pitch on mount.
// No click required — users always see something. Caches per title via key.

import { useState, useEffect } from "react";

export default function AIPitch({ title, year, overview, genres = [], type = "movie" }) {
  const [loading, setLoading] = useState(true);
  const [bullets, setBullets] = useState(null);
  const [error, setError] = useState("");

  async function generate() {
    setLoading(true);
    setError("");
    try {
      const res = await fetch("/api/ai-pitch", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title, year, overview, genres, type }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed");
      setBullets(data.bullets || []);
    } catch (e) {
      setError("Couldn't generate. Try again.");
    } finally {
      setLoading(false);
    }
  }

  // Auto-trigger on mount and when title changes
  useEffect(() => {
    if (!title) return;
    setBullets(null);
    generate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [title, year, type]);

  return (
    <div className="rounded-2xl bg-surface border border-border p-5 md:p-6 relative overflow-hidden">
      {/* Animated accent corner */}
      <div className="absolute -top-12 -right-12 w-40 h-40 rounded-full bg-accent-dim blur-3xl pointer-events-none animate-pulse-slow" />
      <div
        aria-hidden
        className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-accent/60 to-transparent"
      />

      <div className="relative flex items-start justify-between gap-4 mb-4">
        <div className="min-w-0">
          <p className="font-mono text-[10px] uppercase tracking-widest2 text-accent mb-1 flex items-center gap-1.5">
            <span className="relative grid place-items-center w-3 h-3">
              <span className="absolute inset-0 rounded-full bg-accent/40 animate-ping" />
              <span className="relative">✦</span>
            </span>
            AI Pitch
          </p>
          <p className="text-sm text-text-2">
            Spoiler-free, 3 bullets, generated for you.
          </p>
        </div>
      </div>

      {loading && (
        <div className="space-y-3 relative">
          {[0, 1, 2].map((i) => (
            <div key={i} className="flex gap-3 items-start">
              <span className="text-accent/40 font-mono shrink-0 mt-0.5">→</span>
              <div
                className="h-4 rounded shimmer flex-1"
                style={{ width: `${88 - i * 6}%` }}
              />
            </div>
          ))}
          <p className="font-mono text-[10px] text-text-3 pt-1">
            Asking the AI…
          </p>
        </div>
      )}

      {error && !loading && (
        <div className="relative">
          <p className="text-sm text-skip mb-2">{error}</p>
          <button
            onClick={generate}
            className="text-xs text-accent hover:text-accent-hover underline-offset-4 hover:underline"
          >
            Try again
          </button>
        </div>
      )}

      {!loading && !error && bullets && bullets.length > 0 && (
        <ul className="relative space-y-2.5 animate-fade-in">
          {bullets.map((b, i) => (
            <li
              key={i}
              className="flex gap-3 text-sm text-text-1 leading-relaxed"
              style={{ animationDelay: `${i * 80}ms` }}
            >
              <span className="text-accent font-mono shrink-0 mt-0.5">→</span>
              <span>{b}</span>
            </li>
          ))}
          <p className="font-mono text-[10px] text-text-3 pt-3 border-t border-border mt-4">
            Generated by Groq · llama-3.3-70b · spoiler-free
          </p>
        </ul>
      )}
    </div>
  );
}
